pluginManagement {
	repositories {
		maven {
			name = "Fabric"
			url = "https://maven.fabricmc.net/"
		}
		maven {
			name = "Forge"
			url = "https://maven.minecraftforge.net/"
		}
		maven {
			name = "Architectury"
			url = "https://maven.architectury.dev/"
		}
		maven {
			name = 'Sponge'
			url = 'https://repo.spongepowered.org/repository/maven-public/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	// Automatic toolchain provisioning
	id("org.gradle.toolchains.foojay-resolver-convention") version("0.10.0")
}

rootProject.name = 'CommandPack'

include(
		'meta',
		'core',
		'vanilla',
		'forge',
		'neo'
)
