plugins {
	id 'dev.architectury.loom' version '1.9.426'
	id 'architectury-plugin' version '3.4.161'
	id 'com.github.johnrengelman.shadow' version '8.1.1'
	id 'maven-publish'
}

architectury {
	platformSetupLoomIde()
	neoForge()
}

loom {
	silentMojangMappingsLicense()
}

configurations {
	common {
		canBeResolved = true
		canBeConsumed = false
	}
	compileClasspath.extendsFrom common
	runtimeClasspath.extendsFrom common
	developmentNeoForge.extendsFrom common
}

repositories {
	maven {
		name = "NeoForge"
		url = "https://maven.neoforged.net/releases"
	}
}

dependencies {
	implementation project(':core')
	neoForge "net.neoforged:neoforge:$rootProject.neoforge"
	minecraft "net.minecraft:minecraft:$rootProject.minecraft"
	mappings loom.officialMojangMappings()
    //common(project(path: ":core", configuration: "namedElements")) { transitive false }
	//implementation "net.neoforged:neoforge:${neoforge}"
	//implementation "net.neoforged.fancymodloader:loader:${fancymodloader}"
	implementation "org.spongepowered:spongeapi:${api}"
	implementation "org.spongepowered:mixin:${mixin}"
	implementation "com.github.SawFowl:LocaleAPI:${localeapi}"
	//implementation fileTree(dir: 'libs', include: '*.jar')
}

jar {
	archiveBaseName = 'part'
}
