plugins {
	id 'java'
	id 'eclipse'
	id 'net.neoforged.moddev' version '2.0.141'
}

neoForge {
	version = neoforge_version
}

dependencies {
	implementation project(':core')
	implementation "org.spongepowered:spongeapi:${api}"
	implementation "org.spongepowered:mixin:${mixin}"
	//annotationProcessor "org.spongepowered:mixin:${mixin}:processor"
	
	implementation fileTree(dir: 'libs', include: '*.jar')
}

jar {
	archiveBaseName = 'part'
}