plugins {
	id 'dev.architectury.loom-no-remap' version '1.17.491'
	id 'architectury-plugin' version '3.5-SNAPSHOT'
	id 'com.github.johnrengelman.shadow' version '8.1.1'
	id 'maven-publish'
}

architectury {
	platformSetupLoomIde()
	neoForge()
}

loom {
	silentMojangMappingsLicense()
}

configurations {
	common {
		canBeResolved = true
		canBeConsumed = false
	}
	compileClasspath.extendsFrom common
	runtimeClasspath.extendsFrom common
	developmentNeoForge.extendsFrom common
}

repositories {
	maven {
		name = "NeoForge"
		url = "https://maven.neoforged.net/releases"
	}
}

dependencies {
	implementation project(':core')
	neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"
	minecraft "com.mojang:minecraft:$rootProject.minecraft_version"
	implementation "org.spongepowered:spongeapi:${api}"
	implementation "org.spongepowered:mixin:${mixin}"
	implementation fileTree(dir: 'libs', include: '*.jar')
}

// ТОЛЬКО ЗАМЕНА ПЛЕЙСХОЛДЕРОВ
processResources {
	filesMatching('META-INF/neoforge.mods.toml') {
		expand(
			version: project.version,
			minecraft_version: rootProject.minecraft_version,
			neoforge_version: rootProject.neoforge_version,
			api: rootProject.api,
			localeapi: rootProject.localeapi
		)
	}
}

jar {
	archiveFileName = 'part.jar'
}
