modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0"

issueTrackerURL = "https://discord.gg/7xnZGSYJH9"
modUrl="https://ore.spongepowered.org/Semenkovsky_Ivan/CommandPack"

[[mods]]
modId = "commandpack"
version = "${version}"
displayName = "CommandPackNeo"
description = "The Essentials plugin analog. The plugin is loaded as a NeoForge mod for using mixins. This may not be necessary in the future."
authors = "SawFowl"
mainClass = "sawfowl.commandpack.CommandPackNeo"

[[mixins]]
config = "commandpack.mixins.neoforge.json"

[[dependencies.commandpack]]
modId = "neoforge"
type = "optional"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.commandpack]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.commandpack]]
modId = "spongeapi"
type = "required"
versionRange = "[${api},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.commandpack]]
modId = "localeapi"
type = "required"
versionRange = "[${localeapi},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.commandpack]]
modId = "h2driver"
type = "optional"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.commandpack]]
modId = "mysqldriver"
type = "optional"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"
